Repository hcsp/binary-tree-dfs-bfs, pull requests merged in 2019-11, with the labels that each got.

#12 Update BinaryTree.java
  src/main/java/com/github/hcsp/algorithm/BinaryTree.java
Labels: is:answer

#13 练习二叉树遍历
  src/main/java/com/github/hcsp/algorithm/BinaryTree.java
Labels: from:VIP, is:answer

#14 binary-tree-dfs-bfs
  src/main/java/com/github/hcsp/algorithm/BinaryTree.java
Labels: is:answer

#15 二叉树的深度优先遍历和广度优先遍历
  src/main/java/com/github/hcsp/algorithm/BinaryTree.java
Labels: from:VIP, is:answer

#16 Modify the test
  src/test/java/com/github/hcsp/algorithm/BinaryTreeTest.java
Labels: from:VIP, is:enhancement

#17 BFS & DFS
  src/main/java/com/github/hcsp/algorithm/BinaryTree.java
Labels: from:VIP, is:answer

#18 广度优先遍历 + 深度优先遍历 及 递归二叉树
  src/main/java/com/github/hcsp/algorithm/BinaryTree.java
Labels: from:VIP, is:answer

#20 完成二叉树的深度优先遍历和广度优先遍历
  src/main/java/com/github/hcsp/algorithm/BinaryTree.java
Labels: from:VIP, is:answer

#21 广度 深度优先遍历
  src/main/java/com/github/hcsp/algorithm/BinaryTree.java
Labels: from:VIP, is:answer
